blog/urls.py
from django.urls import path
from .views import *

app_name='blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/new/', post_new, name='post_new'),
    path('post/<int:pk>/edit/', post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', post_delete, name='post_delete'),
    path('post/<int:pk>/comment/', add_comment, name='add_comment'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views  #builtin views from app for pass change and reset. we dnt create

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    #password complete
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'), #PasswordChangeView is class view so as_view() ad in the end
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('matrimony.urls')),
    
]

#when password change or reset all are already available by django
#password_change
#password_change_done

#password_reset.  In this page email snd
#password_reset_done. after email snd to the user for change pass
#password_reset_confirm  email link which redirect to set new password
#password_reset_complete

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # for images

matrimony/urls.py
from django.urls import path
from .views import *

app_name='matrimony'

urlpatterns = [
    path('new_profile/', ProfileCreateView.as_view(), name='new_profile'), #CREATE
    path('', ProfileListView.as_view(), name='profile_list'), #READ
    path('<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'), #READ
    path('<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'), #UPDATE
    path('<int:pk>/delete/', ProfileDeleteView.as_view(), name='profile_delete'), #DELETE
    path('contact/', ContactView.as_view(), name='contact'),#FORM
    path('example/', ExampleTemplate.as_view(), name='example'),#TEMPLATE
]

matrimony/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)

#https://www.youtube.com/watch?v=phGHOMpukbk&list=PLva9wMNinRL5y-S9HBrnp23SSopHbMKby&index=6
#https://www.youtube.com/watch?v=N0s5hGTBnVs&list=PLva9wMNinRL5y-S9HBrnp23SSopHbMKby&index=7
# Create your models here.
#If your model already have data and you create new models and sec it will show error. so you should use (null=True)

class Religion(models.Model):  #one to many relation ORM as one Religion contain of many people(profiles)
    name= models.CharField(max_length=100)
    def __str__(self): # self function is to call by name not by object1 like that
        return self.name

class Sect(models.Model): ##one to many relation ORM as one Religion contain of many sections like shia & suni 
    name= models.CharField(max_length=100)
    religion=models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='sects') # Foreign key create in many model and then cal single model init
    def __str__(self):
        return self.name

class Caste(models.Model): # one to many as many profiles has one cast
    name= models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Hobbies(models.Model): #many to many relation with profile model as multipe hobbies are in same profile or multiple profile has same hobby
    name= models.CharField(max_length=100)
    
    class Meta: #by default in django admin it shows 'hobbys' which is wrong spells u can correct bt this
        verbose_name_plural="Hobbies"
    
    def __str__(self):
        return self.name
    
class FatherProfile(models.Model): # one to one model relation
    name=models.CharField(max_length=100)
    occupation=models.CharField(max_length=100,null=True, blank=True) #if not want to define
    def __str__(self):
        return self.name


class Profile(models.Model):
    GENDER_COICES=[
        ('M','Male'),
        ('F','Female'),
    ]
    name=models.CharField(max_length=100)
    profile_pic=models.ImageField(null=True, blank=True)   # pip install Pillow
    age=models.IntegerField()
    gender=models.CharField(max_length=1, choices=GENDER_COICES)
    occupation=models.CharField(max_length=100,null=True, blank=True) #if not want to define
    birth_date=models.DateField(null=True)
    is_married=models.BooleanField(default=False)
    email=models.EmailField(max_length=254, unique=True) #unique email for every new data
    
    religion=models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='profiles', null=True) # related_name='profiles' is to show profiles of same religion in religion model
    Sect=models.ForeignKey(Sect, on_delete=models.CASCADE, related_name='profiles', null=True)
    caste=models.ForeignKey(Caste, on_delete=models.CASCADE, related_name='profiles', null=True) #for one to many relation Foreign key used. Foreign key create in many model and then cal single model init
    hobbies=models.ManyToManyField(Hobbies, related_name='profiles') #many to many relation could be ad in any of model
    father=models.OneToOneField(FatherProfile, related_name='dependent', on_delete=models.CASCADE, null=True, blank=True) # related_name='dependent'. show with dependent name tablr in FatherProfile model
    
    def save(self, *args, **kwargs):  #when click on save button following task shown to user
        print(f"Data Updated for {self.name}")
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

matrimony/forms.py
from django import forms
from .models import *

from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError

def my_email_validator(email):
    if email.split('@')[1].split('.')[0].lower() == 'hotmail':
        raise ValidationError("Email Not Acceptable")


class ContactForm(forms.Form):
    name=forms.CharField(max_length=100)
    email = forms.CharField(validators=[EmailValidator(),my_email_validator])
    verify_email = forms.CharField()
    message=forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super().clean()

        name = cleaned_data.get('name')
        cleaned_data['email'] = cleaned_data.get('email').lower()
        cleaned_data['verify_email'] = cleaned_data.get('verify_email').lower()
        message = cleaned_data.get('message')

        if cleaned_data.get('email') != cleaned_data.get('verify_email'):
            raise forms.ValidationError("Email Mismatch")
        
        return cleaned_data
    
class ProfileForm(forms.ModelForm):
    class Meta: # call existing model in that model
        model= Profile
        fields= "__all__"  # ad all fields from Profile model
        #fields= ['name', 'age', 'gender'] #ad specific fields
         #exclude = ['name', 'age', 'gender']




































# from django import forms

# from django.core.validators import EmailValidator
# from django.core.exceptions import ValidationError

# def my_email_validator(email): #custom email validator
#     if email.split('@')[1].split('.')[0].lower() == 'hotmail': #email.split('@') split into two parts before[0] and after[1] @. [1](which is gmail.com).split('.')(split into two parts bfore[0] after[1].)[0]([0]is 'gmail' and 'com'is[1])
#         raise ValidationError("Email Not Acceptable")


# class ContactForm(forms.Form):
#     name=forms.CharField(max_length=100)
#     email = forms.CharField(validators=[EmailValidator(),my_email_validator])
#     verify_email = forms.CharField()
#     message=forms.CharField(widget=forms.Textarea)

#     def clean(self): # this clean function itself called u dnt need to cal beacause in ContactView (if form.is_valid():) this will call that clean function
#         cleaned_data = super().clean() # default method you need to use in clean always. super() is to run default clean method

#         name = cleaned_data.get('name')

#     # Lowercasing email and verify_email if they exist
#         email = cleaned_data.get('email')
#         if email:
#             cleaned_data['email'] = email.lower()

#         verify_email = cleaned_data.get('verify_email')
#         if verify_email:
#             cleaned_data['verify_email'] = verify_email.lower()

#         message = cleaned_data.get('message')

#     # Checking if email and verify_email match
#         if cleaned_data.get('email') != cleaned_data.get('verify_email'):
#             raise forms.ValidationError("Email Mismatch")
    
        
#         return cleaned_data
    

        


    

        

    

matrimony/views.py
from .models import Profile
from .forms import ContactForm, ProfileForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, FormView
from django.views.generic import ListView, DetailView, DeleteView,UpdateView, TemplateView

# Class Base Views
#CURD
#CREATE
class ProfileCreateView(LoginRequiredMixin, CreateView):
    model= Profile # model which we used
    form_class= ProfileForm # fields define
    template_name= 'matrimony/new_profile.html'
    success_url= reverse_lazy ('matrimony:profile_list')
    
# READ 
class ProfileListView(ListView):
    model= Profile # it creates profile_list
    template_name= 'matrimony/profile_list.html'
    
class ProfileDetailView(DetailView):
    model= Profile
    template_name= 'matrimony/profile_detail.html'


# UPDATE
class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model= Profile # model which we used
    form_class= ProfileForm # fields define
    template_name= 'matrimony/new_profile.html'
    success_url= reverse_lazy ('matrimony:profile_list')


# DELETE 
class ProfileDeleteView(LoginRequiredMixin, DeleteView):
    model= Profile # model which we used
    template_name= 'matrimony/confirm_delete.html'
    success_url= reverse_lazy ('matrimony:profile_list')

#FORM
class ContactView(FormView):
    template_name = 'matrimony/contact.html'
    form_class = ContactForm
    success_url= reverse_lazy ('matrimony:contact')
    
    def get_context_data(self, **kwargs): # if you want to show specific thing
        context = super().get_context_data(**kwargs) # this is for alredy added
        context["user"] = self.request.user # updated
        return context

#TEMPLATE
class ExampleTemplate(TemplateView):  # if u want to open one templete from one link
    template_name = 'matrimony/example.html'

matrimony/templates/matrimony/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Are you sure you want to delete this?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}       
        <button type="submit" class="btn btn-primary" value="Submit">Yes Delete </button>
    </form>
{% endblock %}

matrimony/templates/matrimony/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Contact US!</h1>
    <form method="post">
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" class="form-control" name="{{ form.name.name }}">
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control" name="{{ form.email.name }}">
        </div>
        <div class="form-group">
            {{ form.verify_email.label_tag }}
            <input type="email" class="form-control" name="{{ form.verify_email.name }}">
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}
            <textarea class="form-control" name="{{ form.message.name }}"></textarea>
        </div>

        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

matrimony/templates/matrimony/example.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <h1>Example Template</h1>
</div>
{% endblock %}

matrimony/templates/matrimony/new_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>Enter Profile Details</h1>
    <form method="post" enctype="multipart/form-data" ><!--  enctype="multipart/form-data" . used that that if yoy have pics, videos likethat -->
        {{ form.as_p }}

        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock %}

matrimony/templates/matrimony/profile_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ profile.profile_pic.url }}" class="card-img" alt="Profile picture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ profile.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ profile.age }} years old</small></p>
                            <p class="card-text">{{ profile.bio }}</p>
                            <p class="card-text">
                                <strong>Occupation:</strong> {{ profile.occupation }}<br>
                                <strong>Date of Birth:</strong> {{ profile.birth_date }}<br>
                                <strong>Marital Status:</strong> {{ profile.is_married|yesno:"Married,Single" }}<br>
                                <strong>Email:</strong> {{ profile.email }}<br>
                                <strong>Hobbies:</strong> 

                                <ul>
                                    {% for hobby in profile.hobbies.all  %}
                                    <li>{{ hobby.name }}<br></li>
                                    {% endfor %}
                                </ul> 

                                <strong>Religion:</strong> {{ profile.religion }}<br>
                                <strong>Sect:</strong> {{ profile.Sect }}<br>
                                <strong>Caste:</strong> {{ profile.caste }}<br>
                                <strong>Father's Name:</strong> {{ profile.father.name }}<br>
                                <strong>Father's Occupation:</strong> {{ profile.father.occupation }}<br>
                                
                            </p>
                            <hr>
                            <a href="{% url 'matrimony:profile_list' %}" class="btn btn-primary">Back</a>
                            <a href="{% url 'matrimony:profile_update' profile.id %}" class="btn btn-warning">Update</a>
                            <a href="{% url 'matrimony:profile_delete' profile.id %}" class="btn btn-danger">Delete</a>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

matrimony/templates/matrimony/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <a href="{% url 'matrimony:new_profile' %}" class="btn btn-warning">Add Profile</a>
    <hr>
    <div class="row">
        {% for profile in profile_list %}
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="{{ profile.profile_pic.url }}" alt="Profile picture" width="300" height="400">
                <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <a href="{% url 'matrimony:profile_detail' profile.id %}" class="btn btn-primary">View Profile</a>
                </div>
            </div>
            <p></p>
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}